name: Test host-details function
description: Workflow to invoke the host-details function
provision_on_install: true
trigger:
    next:
        - host_details_6d220b7a
    name: On demand
    parameters:
        properties:
            host_id:
                type: string
                title: Host ID
        required:
            - host_id
        type: object
actions:
    host_details_6d220b7a:
        id: functions.host-details.host-details
        properties:
            host_id: ${host_id}
