name: Test host-details function
description: Workflow to invoke the host-details function
provision_on_install: true
trigger:
    next:
        - host_details_6d220b7a
actions:
    host_details_6d220b7a:
        id: functions.host-details.host-details
        properties:
            host_id: "8f3e99d73be8434a83d9d328c02ce3ab"
