name: Test hello function
description: Workflow to invoke the hello function
provision_on_install: true
trigger:
    next:
        - hello_a43c7da4
actions:
    hello_a43c7da4:
        id: functions.hello.hello
        properties:
            name: George
